Zadatak8
vkrekic-endava/vladimir-java-zadaci pull request #10
Opened 2018-10-09 14:39 UTC by vkrekic-endava

2018-10-09 15:34 UTC, endavamarko commented on src/Zadatak8/Firma.java
> +        lista = lista;
Ovde  dodeljujes jednu istu promenljivu samoj sebi

2018-10-09 16:04 UTC, BoskoNikolic requested changes

2018-10-09 16:04 UTC, BoskoNikolic commented on src/Zadatak8/Firma.java
> +    public Map<Proizvod, Integer> lista;
Po pravilu bi i ovo trebalo da bude private i da mu se pristupa preko get/set

2018-10-09 16:04 UTC, BoskoNikolic commented on src/Zadatak8/Firma.java
> +    public Map<Proizvod, Integer> porudzbina(Map<Proizvod, Integer> lista, Proizvod proizvod, int kolicina){
Nikad ne vracas vrednost ove metode.

2018-10-09 16:04 UTC, BoskoNikolic commented on src/Zadatak8/Kafe.java
> +    public String toString() {
Poenta toString je bila da se vezba overried. Sad mozes da ga izbacis iz zadatka.

2018-10-09 16:04 UTC, BoskoNikolic commented on src/Zadatak8/Main.java
> +        System.out.println("***********************************************************************************");
napravi konstante od svih stringova koji ti se ponavaljaju.

2018-10-09 16:04 UTC, BoskoNikolic commented on src/Zadatak8/Main.java
> +                System.out.println(k + "........Kolicina: " + v));
npr ovaj se ponvalja vise puta

2018-10-09 16:12 UTC, BoskoNikolic commented on src/Zadatak8/Main.java
> +        System.out.printf("Pokusaj skidanja %d komada %s %s%n", 32, proizvod1.getImeProizvoda(), ((Sokovi) proizvod1).getSirovina());
ako definises proizvod1 kao Sokovi ond ne treba da cast-ujes promeljivu ovde. Vidi sta ce se destiti ako to to uradis.

2018-10-10 10:11 UTC, BoskoNikolic approved these changes

2018-10-10 10:17 UTC, merged