Dodat Zadatak1/HelloWorld
vkrekic-endava/vladimir-java-zadaci pull request #2
Opened 2018-10-03 14:52 UTC by vkrekic-endava

2018-10-03 16:22 UTC, endavamarko approved these changes
I approve!

2018-10-03 20:56 UTC, BoskoNikolic requested changes

2018-10-03 20:56 UTC, BoskoNikolic commented on src/Zadatak1/HelloWorld.java
> +  ZADATAK1: Kreirati projekat u razvojnom okruženju (Eclipse, IntelliJ)
Spoj tekst zadatka i ime autora u jedan java doc

2018-10-03 21:22 UTC, BoskoNikolic requested changes

2018-10-03 21:22 UTC, BoskoNikolic commented on src/Zadatak1/HelloWorld.java
> + * AUTOR: Vladimir Krekic
koristi java doc tag @author

2018-10-04 09:59 UTC, BoskoNikolic approved these changes

2018-10-04 10:11 UTC, merged