Dodavanje drugog zadatka
vkrekic-endava/vladimir-java-zadaci pull request #3
Opened 2018-10-03 15:19 UTC by vkrekic-endava

2018-10-03 15:59 UTC, endavamarko commented on src/Zadatak2/Pogadjanje.java
> +            }
Ovde treba dodati finaly i tu moze da se zatvori scanner varijabla npr. finally {
    if(scanner!=null)
        scanner.close();
}
Ili zatvoriti na drugom mestu, svakako treba to uraditi

2018-10-03 21:20 UTC, BoskoNikolic requested changes
Zadatak ne bi tebalo da svaki put generise novi random broj nego da da korisniku sansu da pogadja isti broj. 
Isto tako ne treba pokrenuti celu igru iz pocetka ako nije unet broj izmedju 1 i 50.

2018-10-03 21:20 UTC, BoskoNikolic commented on src/Zadatak2/Pogadjanje.java
> +    private static int broj;
Kako je trenutno program napisan ovo je lokalna promenljiva, pa je treba definisati dole u okviru main-a.

2018-10-03 21:20 UTC, BoskoNikolic commented on src/Zadatak2/Pogadjanje.java
> +                System.out.println("Niste uneli broj");
"Niste uneli broj, pokusajte opet" ili tako nesto. Zelimo da korisnik ne mora da razmislja sta mu je iduci korak.

2018-10-03 21:43 UTC, BoskoNikolic commented on src/Zadatak2/Pogadjanje.java
> +                broj = scanner.nextInt();
mozda da napravis posebnu metodu za proveru ispravnosti unetog karaktera. na taj nacin smanjujes kognitivnu kompleksnost koda i povesavas citljivost.

2018-10-05 09:39 UTC, BoskoNikolic requested changes
Pogledaj komentare, i pokusaj da ih implementiras.

2018-10-05 09:39 UTC, BoskoNikolic commented on src/Zadatak2/Pogadjanje.java
> +                        break;
Po jednom, od silnih, pravila pisanja lepog koda, unutar while-a/if-a itd. treba imati samo jedan break/continue.
Ovde mozes uvesti pomocni boolean koji ce ti omoguciti izlaz iz while-a.

2018-10-05 13:31 UTC, BoskoNikolic requested changes
Sto se mene tice mozes da komitujes.

2018-10-05 13:32 UTC, BoskoNikolic approved these changes

2018-10-05 13:34 UTC, merged