dodat i cetvrti zadatak
vkrekic-endava/vladimir-java-zadaci pull request #4
Opened 2018-10-03 15:36 UTC by vkrekic-endava

2018-10-03 21:38 UTC, BoskoNikolic requested changes
Napravi jednu metodu koja ce citati uneseni broj i proveravati njegovu ispravnost. Nema potrebe da 3 puta pises isti kod za proveru unosa (kad unostis duzinu niza, elemente niza i broj koji se trazi).

2018-10-03 21:38 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +        //Moj kod za BoubleSort
Uvek brisi zakomentarisani kod pre nego sto posaljes file na code review.

2018-10-03 21:38 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +  ZADATAK4: Za uneti niz celih brojeva duzine n (koja se takođe unosi),
Moja greska nisam eksplicitno naveo u zadatku, ali ako nije problem da ispravis, duzina niza ne sme biti manja od 5 (posto stampas prvih 5 clanova). Treba i kod malo da izmenis.

2018-10-03 21:38 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +            System.out.print("Unesite " + (brojac1+1) + ". clan niza (samo cele brojeve): ");
Koristi StringBuilder umesto konkatenacije stingova

2018-10-03 21:38 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +        String poruka = (pronadji(niz, trazeniBroj))? "Broj " + trazeniBroj + " je clan niza" : "Broj " + trazeniBroj + " nije clan niza";
Isto kao linija 43.

2018-10-03 21:38 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +            System.out.print("Unesite duzinu niza: ");
println

2018-10-03 21:38 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +        //Unosi clanove niza i ponavlja samo za one koji ne budu isptavno ineti
typo

2018-10-03 21:41 UTC, BoskoNikolic requested changes

2018-10-03 21:41 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +        int lngNiza = (duzinaNiza>5)? 5: duzinaNiza;
Izbegavaj nejasna imena promenljivih poput ove lngNiza

2018-10-03 21:41 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +        int lngNiza = (duzinaNiza>5)? 5: duzinaNiza;
Mozes, npr da stampanje niza stavis u posebnu metodu, kako bi "main" deo programa bio sto manji i sto citljiviji.

2018-10-05 07:42 UTC, BoskoNikolic requested changes
Sitne korekcije

2018-10-05 07:42 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +            System.out.printf("Unesite %d. clan niza (samo cele brojeve): \n", (brojac+1));
Ovde iskoristi %n umesto /n da bi dobio "platform-specific" new line.

2018-10-05 07:42 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +            System.out.printf("%d. clan niza je %d\n",(brojac+1), niz[brojac]);
Isto kao na linij 74

2018-10-05 07:42 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +        System.out.println(poruka);
Kada se koristi StringBuilder uvek .toString na kraju

2018-10-05 07:42 UTC, BoskoNikolic commented on src/Zadatak4/Niz.java
> +        if(poruka.equals(ZA_DUZINU_NIZA)) {
mozes ovaj if/else kao posebnu metodu, da povecas citljivost programa.

2018-10-05 10:27 UTC, endavamarko commented on src/Zadatak4/Niz.java
> +    //Unosi duzinu niza ili broj za retragu, zavisno od stringa
Ako se vec pisu komentari metoda onda je najbolje da budu u obliku JavaDoc, a ovi obicni komentari idu u telo metode. JavaDoc format je:
/**

    opis metoda
    @param navedeni parametri ako ih ima
    @return naveden povratni tip ako nije void
    */

2018-10-05 13:49 UTC, BoskoNikolic approved these changes

2018-10-05 14:06 UTC, endavamarko approved these changes

2018-10-05 14:25 UTC, merged