Zadatak5 draft
vkrekic-endava/vladimir-java-zadaci pull request #7
Opened 2018-10-04 16:24 UTC by vkrekic-endava

2018-10-06 12:02 UTC, BoskoNikolic requested changes
Generalna zamerka je na nazive get/set metoda i promenljivih. 
getPoluprecnikKruga je mnogo citljivije nego getPoluprecnik1

2018-10-06 12:02 UTC, BoskoNikolic commented on src/Zadatak5/NejednakostranicniTrougao.java
> +    public double visina(){
private

2018-10-06 12:02 UTC, BoskoNikolic commented on src/Zadatak5/GeometrijskaSlika.java
> +    public GeometrijskaSlika(double obim) {
neka me ostali isprave ako gresim, ali zar ne bi trebalo konstruktor abstract clase da bude protected?

2018-10-06 12:39 UTC, BoskoNikolic requested changes

2018-10-06 12:39 UTC, BoskoNikolic commented on src/Zadatak5/NejednakostranicniTrougao.java
> +    public double visina(){
Po kojoj formuli tacno racunas visinu?

Mislim da bi ti bilo lakse da is ozracunao povrsinu po heronovm obrascu.

2018-10-06 12:39 UTC, BoskoNikolic commented on src/Zadatak5/NejednakostranicniTrougao.java
> +        double sum = getStranica()+getStranica2()+getStranica3();
ova suma je obim trougla. nemoj duplirati isti kod.

2018-10-06 12:39 UTC, BoskoNikolic commented on src/Zadatak5/NejednakostranicniTrougao.java
> +class NejednakostranicniTrougao extends Trougao{
obrati paznju pod kojim se uslovima moze formirati nejdnakostranicni trougao tj. kakv treba da bude odnos stranica.

2018-10-08 15:59 UTC, endavamarko commented on src/Zadatak5/Trougao.java
> +        return getStranica()*Math.sqrt(3)/4;
Ovde ne valja formula za povrsinu treba da bude stranica na kvadrat

2018-10-08 19:37 UTC, BoskoNikolic requested changes

2018-10-08 19:37 UTC, BoskoNikolic commented on src/Zadatak5/Pravougaonik.java
> +        return 2* getStranicaB()+2*getStranica();
Distributivnost ;)

2018-10-08 19:37 UTC, BoskoNikolic commented on src/Zadatak5/NejednakostranicniTrougao.java
> +class NejednakostranicniTrougao extends Trougao{
Kada nisu unete korektne vrednosti za stranice trougla, nemoj da stampas obim i povrsinu (ni -1) nego samo poruku da nije moguce izracunati.

2018-10-09 12:41 UTC, BoskoNikolic requested changes
Obrati paznju na komentare.

2018-10-09 12:51 UTC, BoskoNikolic requested changes
Sve je ok. Mozes da commit-ujes.

2018-10-09 13:41 UTC, BoskoNikolic approved these changes

2018-10-09 13:42 UTC, merged