Zadatak 7
vkrekic-endava/vladimir-java-zadaci pull request #9
Opened 2018-10-09 09:04 UTC by vkrekic-endava

2018-10-09 15:30 UTC, BoskoNikolic requested changes
Pokusaj da implementiras komentare.  Takodje obrisi sav "unused" kod. Sve gete/set metode koje ne koristis, ne treba da stoje u kodu.

2018-10-09 15:30 UTC, BoskoNikolic commented on src/Zadatak7/IOmetode.java
> +    private IOmetode() {
Ime klase bas ruzno, izbegavaj ovakve nazive. takodje M u "metode" je trebalo da bude velikim slovom.

2018-10-09 15:30 UTC, BoskoNikolic commented on src/Zadatak7/IOmetode.java
> +            String ime = unesiIme("ime");
Da malo zakomplikujemo zadatak, obezbedi da prvo slovo imena i prezimena bude uvek veliko

2018-10-09 15:30 UTC, BoskoNikolic commented on src/Zadatak7/IOmetode.java
> +        ArrayList<Student> spisak = new ArrayList<>();
Koristi List umesto ArrayList

2018-10-09 15:30 UTC, BoskoNikolic commented on src/Zadatak7/IOmetode.java
> +            e.printStackTrace();
stampaj poruku unutar system.out ...

2018-10-09 15:30 UTC, BoskoNikolic commented on src/Zadatak7/IOmetode.java
> +    private static Scanner scanner = new Scanner(System.in);
neki poseban razlog zastoje static?

2018-10-09 15:30 UTC, BoskoNikolic commented on src/Zadatak7/Student.java
> +class Student implements Comparable<Student>{
Izmeni kod da ne implementiras Comparable

2018-10-09 15:30 UTC, BoskoNikolic commented on src/Zadatak7/Student.java
> +    public String toString() {
Posto tekstom zadatka nije definisano, nemoj da override-ujes toString(). Koriti neku drugu metodu

2018-10-09 15:30 UTC, BoskoNikolic commented on src/Zadatak7/Student.java
> +    @Override
Nemoj da override-ujes compareTo

2018-10-09 15:30 UTC, BoskoNikolic commented on src/Zadatak7/IOmetode.java
> +            System.out.println("Zelite li da sacuvate uneto ('d/D' za DA, ostali tasteri za nastavak unosa)");
Izmeni komentar, malo je nejasan. Bolje pitaj da li zelite da nastavite sa unosom studenata ili da stampate spisak

2018-10-09 15:30 UTC, BoskoNikolic commented on src/Zadatak7/IOmetode.java
> +                sacuvaj(spisak);
Stampaj poruku sa lokacijom i imenom file-a. Korisnik nema pojma gde treba da je trazi.

2018-10-10 10:01 UTC, BoskoNikolic requested changes
unos podataka ne radi najbolje.

2018-10-10 10:01 UTC, BoskoNikolic commented on src/Zadatak7/ObradaZahteva.java
> +            }catch (InputMismatchException e){
Prazan catch blok

2018-10-10 10:01 UTC, BoskoNikolic commented on src/Zadatak7/ObradaZahteva.java
> +            e.printStackTrace();
Ovo nisi ispravio. Stampaj exception na standardni izlaz

2018-10-10 10:01 UTC, BoskoNikolic commented on src/Zadatak7/ObradaZahteva.java
> +            System.out.println("Lista sacuvana u fajlu C:\\Users\\Vladimir.Krekic\\Metropoliten\\vladimir-java-zadaci\\ocene.txt");
Da li ce ovo biti putanja i na mom racunaru ? C:\\Users\\Vladimir.Krekic\\Metropoliten\\

Definisi relativnu putanje. Najbolje da stampas file u istom folderu gde je i zadatak, tako uvek znas gde ce biti.

2018-10-10 10:01 UTC, BoskoNikolic commented on src/Zadatak7/Main.java
> +        ObradaZahteva io = ObradaZahteva.getInstance();
rekli smo da necemo jednoslovne/dvoslovne promenljive koj nisu dovoljno deskriptivne

2018-10-10 10:01 UTC, BoskoNikolic commented on src/Zadatak7/ObradaZahteva.java
> +    private String unesiIme (String poruka){
Uneo sam ime   "fdsf ()"

Uneo sam prezime "fdsfsd ()"

Zadatak ti poludi ako je u imenu ili prezimenu specijalni karakter (ukljucujuci i apostrof). Probaj sam . 
Nisi ispostovao komentar da imena i prezimena teba da pocnu obavezno velikim slovom.

2018-10-10 10:37 UTC, vkrekic-endava commented on src/Zadatak7/ObradaZahteva.java
> +    private String unesiIme (String poruka){
Ispravio sam za apostrof.
Nisam imao problema kod unosa specijalnih karaktera. Javi mi pogresno uneto ime i prezime i program nastavi normalno da radi.
Ako korisnik unese ime ili prezime sa pocetnim malim slovom program ne prijavljuje gresku nego sam izvrsi ispravke - linija 89.

2018-10-10 15:04 UTC, BoskoNikolic requested changes

2018-10-10 15:04 UTC, BoskoNikolic commented on src/Zadatak7/ObradaZahteva.java
> +            System.out.println(e.getStackTrace());;
Imas dva ; znaka

2018-10-10 15:04 UTC, BoskoNikolic commented on src/Zadatak7/ObradaZahteva.java
> +    private String unesiIme (String poruka){
program ne radi ako se za ime unese vise od jedne reci.

2018-10-11 14:17 UTC, BoskoNikolic commented on src/Zadatak7/ObradaZahteva.java
> +    private String unesiIme (String poruka){
sve radi odlicno.

2018-10-11 14:17 UTC, BoskoNikolic approved these changes

2018-10-11 14:42 UTC, endavamarko approved these changes

2018-10-11 15:00 UTC, merged